Rver cancels subscriptions on correct gall ducts and cancels behn timers correctly as well
urbit/arvo pull request #1192
Opened 2019-06-14 18:38 UTC by loganallenc

2019-06-14 18:47 UTC, eglaysher approved these changes

2019-06-14 20:07 UTC, joemfb requested changes
The timer handling needs some tweaks, details below:

2019-06-14 20:07 UTC, joemfb commented on sys/vane/rver.hoon
> +          $%  [%wake error=(unit tang)]
This is just half of the necessary timer fix. A `%wake` where `error` is `~` is a normal timer, but when `error` is present it's a report of a previously-failed timer event. The fully correct way to handle this is to unwind whatever state was associated with that timer (maybe canceling subscriptions, builds, producing an HTTP 500 response etc.). The less correct approach is to just print the error via `%dill` if present (this is what most vanes are doing right now). But it's not correct to treat such an event as a normal timer wakeup.

2019-06-27 05:43 UTC, joemfb commented
contained-in/superceded-by #1202

2019-06-27 21:15 UTC, loganallenc commented
Closing this as it is superseded by the Modulo merge PR.

2019-06-27 21:15 UTC, closed without merging